version: 2

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build && yarn export
      - run: mv out /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - *attach_workspace
      - run: sudo pip install awscli
      - run: aws s3 sync /tmp/workspace/out s3://deviceplane.com/ --delete
      - run: aws cloudfront create-invalidation --distribution-id EFCZOA92U9L6B --paths "/*"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
