version: 2

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.55.5
    steps:
      - *attach_workspace
      - checkout
      - run: hugo
      - run: mv public /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - public

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - *attach_workspace
      - run: sudo pip install awscli
      - run: aws s3 sync /tmp/workspace/public s3://oogi.deviceplane.com/ --delete
      - run: aws cloudfront create-invalidation --distribution-id E2KFV7IQT7GKT3 --paths "/*"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
